rvohealth/psychic

openapi.json
package.json
spec/unit/openapi-renderer/endpoint/toPathObject.spec.ts
spec/unit/openapi-renderer/serializer/parse.spec.ts
test-app/src/app/controllers/PetsController.ts
test-app/src/app/models/Post.ts
test-app/src/app/models/User.ts
test-app/src/app/serializers/PostSerializer.ts
test-app/src/conf/routes.ts
test-app/src/db/migrations/1721579300508-create-posts.ts
test-app/src/types/db.ts
test-app/src/types/dream.ts
yarn.lock

`paramSafeColumns` are omitted from the
request body in OpenAPI specs

Ensure that columns explicitly omitted from

---

.yarnrc.yml
client/package.json
client/yarn.lock
package.json
yarn.lock

close https://github.com/rvohealth/psychic/security/dependabot/32
close https://github.com/rvohealth/psychic/security/dependabot/31

bump vitest, vite to close dependabot alerts

---

package.json
spec/unit/psychic-application/services.spec.ts
src/psychic-application/helpers/import/importServices.ts
test-app/src/app/services/GlobalNameCompatibleClass.ts
test-app/src/app/services/Nested/GlobalNameCompatibleClass.ts
test-app/src/app/services/NoDefaultExportClass.ts
test-app/src/app/services/NoGlobalNameClass.ts
test-app/src/app/services/functions/globalNameIncompatibleFunction.ts
test-app/src/app/services/functions/noDefaultExportFunction.ts
test-app/src/conf/app.ts

expect it to be set via `setGlobalName`

Only set global name on classes that

---

client/package.json
client/yarn.lock
yarn.lock

close https://github.com/rvohealth/psychic/security/dependabot/38
close https://github.com/rvohealth/psychic/security/dependabot/37

bump vite to 6.2.6

---

admin.openapi.json
mobile.openapi.json
package.json
spec/unit/openapi-renderer/app/buildOpenapiObject.spec.ts
spec/unit/openapi-renderer/app/sync.spec.ts
spec/unit/openapi-renderer/endpoint/toSchemaObject.spec.ts
src/openapi-renderer/endpoint.ts
test-app/src/app/controllers/OpenapiDecoratorTestsController.ts
test-app/src/app/serializers/CommentSerializer.ts
test-app/src/conf/routes.ts
test-app/src/types/dream.ts

close https://rvohealth.atlassian.net/browse/PDTC-7537

fix openapi bug causing alternate openapi specs to produce invalid schema

---

openapi.json
package.json
spec/unit/openapi-renderer/app/buildOpenapiObject.spec.ts
spec/unit/openapi-renderer/endpoint/toPathObject.spec.ts
spec/unit/openapi-renderer/endpoint/toSchemaObject.spec.ts
spec/unit/openapi-renderer/serializer/parse.spec.ts
src/openapi-renderer/body-segment.ts
src/openapi-renderer/endpoint.ts
src/openapi-renderer/helpers/primitiveOpenapiStatementToOpenapi.ts
test-app/src/app/controllers/ParamsTestController.ts
test-app/src/app/models/User.ts
test-app/src/app/serializers/CommentSerializer.ts
yarn.lock

close https://rvohealth.atlassian.net/browse/PDTC-7538

remove string null from computed enum values

---

openapi.json
package.json
spec/unit/controller/params.spec.ts
spec/unit/openapi-renderer/endpoint/toPathObject.spec.ts
spec/unit/scenarios/params/openapi-validation.spec.ts
spec/unit/server/params.spec.ts
src/helpers/alternateParamName.ts
src/helpers/isArrayParamName.ts
src/openapi-renderer/body-segment.ts
src/server/params.ts
test-app/src/app/controllers/ParamsTestController.ts
test-app/src/app/controllers/UsersController.ts
test-app/src/conf/routes.ts

close https://rvohealth.atlassian.net/browse/PDTC-7618

enable params to capture array-bracketed values when casting

---

package.json
spec/unit/openapi-renderer/endpoint/toSchemaObject.spec.ts
src/error/openapi/FailedToLookupSerializerForEndpoint.ts
src/openapi-renderer/endpoint.ts

close https://rvohealth.atlassian.net/browse/PDTC-7760

do not splat extendedBy for sti child models

---

client/package.json
client/yarn.lock
package.json
yarn.lock

close https://github.com/rvohealth/psychic/security/dependabot/41

bump react-router

---

openapi.json
spec/unit/openapi-renderer/endpoint/toPathObject.spec.ts
spec/unit/scenarios/pagination.spec.ts
src/openapi-renderer/endpoint.ts
src/openapi-renderer/helpers/pageParamOpenapiProperty.ts
src/openapi-renderer/helpers/safelyAttachPaginationParamsToBodySegment.ts
test-app/src/app/controllers/UsersController.ts
test-app/src/conf/routes.ts

when paginating, provide an api that enables devs to add a page param to either query or requestBody to streamline pagination integration.
close https://rvohealth.atlassian.net/browse/PDTC-7857

add ability to customize query/requestBody shape for page

---

package.json
src/cli/index.ts
src/helpers/path/psychicPath.ts
src/watcher/Watcher.ts

close https://rvohealth.atlassian.net/browse/PDTC-7943
but who is watching the watcher?

add watcher to ensure that sync is always performed

---

spec/unit/generate/initializers/syncEnums.spec.ts
src/generate/initializer/syncEnums.ts

close https://rvohealth.atlassian.net/browse/PDTC-7974

update syncEnums cli tool to new sync hook

---

package.json
spec/unit/controller/params.spec.ts
spec/unit/openapi-renderer/endpoint/toPathObject.spec.ts
src/controller/index.ts
src/openapi-renderer/endpoint.ts
src/server/helpers/paramNamesForDreamClass.ts
test-app/src/app/models/User.ts

close https://rvohealth.atlassian.net/browse/PDTC-7993

enable virtual columns to come through as part of including arg

---

CHANGELOG.md
package.json
src/bin/helpers/printRoutes.ts

close https://rvohealth.atlassian.net/browse/PDTC-8042

fix route printout

---

CHANGELOG.md
package.json
spec/unit/generate/openapi/reduxBindings.spec.ts
spec/unit/scenarios/routing/non-existent-action.spec.ts
src/generate/helpers/reduxBindings/writeApiFile.ts
src/generate/helpers/reduxBindings/writeOpenapiJsonFile.ts
src/router/index.ts
test-app/src/conf/routes.ts

close https://rvohealth.atlassian.net/browse/PDTC-8060

add missing hooks to openapi redux bindings

---

CHANGELOG.md
package.json
spec/unit/generate/helpers/generateController.spec.ts
spec/unit/generate/helpers/generateResourceControllerSpecContent.spec.ts
src/generate/controller.ts
src/generate/helpers/generateResourceControllerSpecContent.ts
src/helpers/path/addImportSuffix.ts
src/helpers/path/relativePsychicPath.ts
src/psychic-app/index.ts
test-app/src/conf/app.ts

related https://rvohealth.atlassian.net/browse/PDTC-8250

add ability to customize import suffixes for generators

---

CHANGELOG.md
package.json
spec/unit/controller/ok.spec.ts
src/controller/index.ts
src/openapi-renderer/endpoint.ts
test-app/src/app/controllers/UsersController.ts
test-app/src/conf/routes.ts
test-app/src/openapi/openapi.json
yarn.lock

close https://rvohealth.atlassian.net/browse/PDTC-8276

fall back to openapi serializer if none provided

---

CHANGELOG.md
package.json
spec/unit/openapi-renderer/endpoint/shouldValidateOpenapiPayload.spec.ts
spec/unit/scenarios/openapi/validation/requestBody.spec.ts
spec/unit/scenarios/openapi/validation/responseBody.spec.ts
spec/unit/scenarios/saving-records.spec.ts
src/error/openapi/OpenapiFileNotFound.ts
src/openapi-renderer/helpers/OpenapiPayloadValidator.ts
src/psychic-app/index.ts
src/psychic-app/openapi-cache.ts
test-app/src/app/controllers/OpenapiValidationTestsController.ts
test-app/src/conf/app.ts
test-app/src/conf/routes.ts
test-app/src/openapi/openapi.json
test-app/src/types/openapi/openapi.d.ts

related https://rvohealth.atlassian.net/browse/PDTC-8453

don't swallow openapi import failures in production

---

CHANGELOG.md
package.json
spec/unit/scenarios/openapi/validation/query.spec.ts
src/controller/index.ts
src/openapi-renderer/helpers/OpenapiPayloadValidator.ts
test-app/src/app/controllers/OpenapiValidationTestsController.ts
test-app/src/conf/routes.ts
test-app/src/openapi/openapi.json
test-app/src/types/openapi/openapi.d.ts

additionally, validate blank strings when allowEmptyValue=false
close https://rvohealth.atlassian.net/browse/PDTC-8477

customize query validation to ensure array encapsulation

---

CHANGELOG.md
package.json
src/router/index.ts
yarn.lock

Draft until we publish Dream as non-beta and update package with that version of Dream

Increase depth of inspection during error logging
